// apps/admin/src/components/atoms/LinkMenu.svelte
<script lang="ts">
  export let to: string;
  export let isActive: boolean = false;
</script>

<a
  href={to}
  un-text="sm"
  class="flex items-center
    py-2 px-4 rounded
    hover:(bg-slate-200 dark:bg-slate-800/50 text-blue-500)
    {isActive
    ? 'bg-slate-200 dark:bg-slate-800/50 text-blue-500'
    : 'dark:text-slate-300 text-slate-600 font-normal'}"
>
  <slot />
</a>

// apps/admin/src/components/atoms/LinkMenu.tsx
import type { Component, JSX } from "solid-js";

type MenuItemSidebarProps<P = {}> = P & { children?: JSX.Element };
type MenuItemSidebarComponent<P = {}> = Component<MenuItemSidebarProps<P>>;

export const LinkMenu: MenuItemSidebarComponent = (props) => {
  return (
    <a
      href="#"
      class="flex items-center
        py-2 px-4 rounded
        text-sm font-normal text-slate-900
        dark:text-slate-300 hover:bg-slate-300 dark:hover:bg-slate-800/50"
    >
      {props.children}
    </a>
  );
};
