// apps/admin/src/components/molecules/UserNav.svelte
<img
  id="avatarButton"
  data-dropdown-toggle="userDropdown"
  data-dropdown-placement="bottom-start"
  class="w-10 h-10 rounded-full cursor-pointer"
  src="https://avatars.githubusercontent.com/u/2002000?v=4"
  alt="User dropdown"
/>
<!-- <div
  id="userDropdown"
  class="z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 block"
  data-popper-reference-hidden=""
  data-popper-escaped=""
  data-popper-placement="bottom-start"
  style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(20px, 70.4px, 0px);"
>
  <div class="py-3 px-4 text-sm text-gray-900 dark:text-white">
    <div>Bonnie Green</div>
    <div class="font-medium truncate">name@flowbite.com</div>
  </div>
  <ul
    class="py-1 text-sm text-gray-700 dark:text-gray-200"
    aria-labelledby="avatarButton"
  >
    <li>
      <a
        href="#"
        class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
      >
        Dashboard
      </a>
    </li>
    <li>
      <a
        href="#"
        class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
      >
        Settings
      </a>
    </li>
    <li>
      <a
        href="#"
        class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
      >
        Earnings
      </a>
    </li>
  </ul>
  <div class="py-1">
    <a
      href="#"
      class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
    >
      Sign out
    </a>
  </div>
</div> -->

// apps/admin/src/components/atoms/UserNav.tsx
import type { Component } from "solid-js";

export const UserNav: Component = () => {
  return (
    <>
      <img
        id="avatarButton"
        data-dropdown-toggle="userDropdown"
        data-dropdown-placement="bottom-start"
        class="w-10 h-10 rounded-full cursor-pointer"
        src="https://avatars.githubusercontent.com/u/2002000?v=4"
        alt="User dropdown"
      />

      {/* <div
        id="userDropdown"
        class="z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 block"
        data-popper-reference-hidden=""
        data-popper-escaped=""
        data-popper-placement="bottom-start"
        style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(20px, 70.4px, 0px);"
      >
        <div class="py-3 px-4 text-sm text-gray-900 dark:text-white">
          <div>Bonnie Green</div>
          <div class="font-medium truncate">name@flowbite.com</div>
        </div>
        <ul
          class="py-1 text-sm text-gray-700 dark:text-gray-200"
          aria-labelledby="avatarButton"
        >
          <li>
            <a
              href="#"
              class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >
              Dashboard
            </a>
          </li>
          <li>
            <a
              href="#"
              class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >
              Settings
            </a>
          </li>
          <li>
            <a
              href="#"
              class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >
              Earnings
            </a>
          </li>
        </ul>
        <div class="py-1">
          <a
            href="#"
            class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
          >
            Sign out
          </a>
        </div>
      </div> */}
    </>
  );
};
