// apps/admin/src/components/organisms/sidebar/SidebarWrapper.tsx
import type { Component, JSX } from "solid-js";

type ParentProps<P = {}> = P & { children?: JSX.Element };
type ParentComponent<P = {}> = Component<ParentProps<P>>;

export const SidebarWrapper: ParentComponent = ({ children }) => {
  return (
    <aside
      class="flex-grow basis-14
        border-r border-slate-300 dark:border-slate-800
        bg-slate-200 dark:bg-stone-900/30"
      aria-label="Sidebar"
    >
      {children}
    </aside>
  );
};

// apps/admin/src/components/organisms/sidebar/SidebarWrapper.svelte
<aside
  id="primaryMenu"
  un-bg="slate-100 dark:stone-900/20 dark:gradient-to-tr"
  un-border="dark:slate-800 r slate-200"
  un-lt-lg="w-full h-screen"
  class="app-scrollbar fixed z-50 top-0 h-screen lt-lg:hidden flex-grow basis-14 dark:from-slate-800 dark:to-slate-900"
  aria-label="Sidebar"
>
  <slot />
</aside>
