// apps/admin/src/components/organisms/main/MainSidebarItemLink.tsx
import type { Component, JSX } from "solid-js";

type ParentProps<P = {}> = P & { to: string; text: string };
type ParentComponent<P = {}> = Component<ParentProps<P>>;

export const MainSidebarItemLink: ParentComponent = ({ to, text }) => {
  return (
    <li>
      <a
        href={to}
        class="block text-slate-700
          dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800/50
          py-2 px-4 text-sm"
      >
        {text}
      </a>
    </li>
  );
};

// apps/admin/src/components/pattern/organisms/main/MainSidebarItemLink.svelte
<script lang="ts">
  export let to: string;
  export let text: string;
  export let isActive: boolean = false;
</script>

<li>
  <a
    href={to}
    un-bg="hover:slate-200 dark:hover:slate-800/50"
    un-text="gray-600 dark:slate-400 sm"
    un-border="l hover:blue-500"
    class="block {isActive
      ? 'border-blue-500 bg-slate-200 dark:bg-slate-800/50'
      : 'border-transparent'} py-2 px-4"
  >
    {text}
  </a>
</li>
